<?php

use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $type = [
            ["type"=>"ACCOUNT", "multilevel"=>false, "system"=>true],
            ["type"=>"CHANNEL", "multilevel"=>false, "system"=>true],

            ["type"=>"BLOG", "multilevel"=>true, "system"=>true],
            ["type"=>"NEWS", "multilevel"=>true, "system"=>true],
            ["type"=>"PRODUCT", "multilevel"=>true, "system"=>false],
            ["type"=>"EVENT","multilevel"=>false, "system"=>true],
            ["type"=>"MEDIA","multilevel"=>false, "system"=>true],

            ["type"=>"JENIS_KELAMIN","multilevel"=>false, "system"=>true],
            ["type"=>"STRATA_PENDIDIKAN","multilevel"=>false, "system"=>true],
            ["type"=>"JENJANG_PENDIDIKAN","multilevel"=>false, "system"=>true],
            ["type"=>"STATUS_PERKAWINAN","multilevel"=>false, "system"=>false],
            ["type"=>"KEWARGANEGARAAN","multilevel"=>false, "system"=>false],
            ["type"=>"AGAMA","multilevel"=>false, "system"=>false],
            ["type"=>"JENIS_PEKERJAAN","multilevel"=>false, "system"=>false],
            ["type"=>"AKREDITASI","multilevel"=>false, "system"=>false],

            ["type"=>"STATUS_ANAK","multilevel"=>false, "system"=>false],
            ["type"=>"STATUS_KEPEGAWAIAN","multilevel"=>false, "system"=>false],
            ["type"=>"GOLONGAN","multilevel"=>false, "system"=>false],
            ["type"=>"JABATAN_FUNGSIONAL","multilevel"=>false, "system"=>false],
            ["type"=>"JABATAN_TUGAS_PTK","multilevel"=>false, "system"=>false],
            ["type"=>"JENIS_PRASARANA","multilevel"=>false, "system"=>false],

            ["type"=>"JENIS_PENDAFTARAN","multilevel"=>false, "system"=>false],
            ["type"=>"JALUR_PPDB","multilevel"=>false, "system"=>false],

            ["type"=>"JENIS_SEMESTER","multilevel"=>false, "system"=>false],

            ["type"=>"JENIS_DOKUMEN","multilevel"=>false, "system"=>false],

            ["type"=>"KELAS","multilevel"=>false, "system"=>false],
        ];

        $kategori = [
            ['parent' => null, 'name' => 'HORECA (Hotel, Restaurant & Cafe)', 'type' => 'CHANNEL'],
            ['parent' => null, 'name' => 'MINI MARKET', 'type' => 'CHANNEL'],
            ['parent' => null, 'name' => 'SUPER MARKET', 'type' => 'CHANNEL'],
            ['parent' => null, 'name' => 'CONVENIENCE STORE (Toko Kelontong)', 'type' => 'CHANNEL'],
            ['parent' => null, 'name' => 'WARUNG', 'type' => 'CHANNEL'],

            ['parent' => null, 'name' => 'INDOMARET', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'CERIA MART', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'ALFAMART', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'ALFAMIDI', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'YOMART', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'CIRCLE K', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'FARMERS MARKET', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'FOODHALL', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'COCO MART', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'RED & WHITE', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'LOTTE', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'GIANT', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'HYPERMART', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'SUPERINDO', 'type' => 'ACCOUNT'],
            ['parent' => null, 'name' => 'INDOGROSIR', 'type' => 'ACCOUNT'],



            ['parent' => null, 'name' => 'programming', 'type' => 'BLOG'],
            ['parent' => null, 'name' => 'travelling',  'type' => 'BLOG'],

            ['parent' => null, 'name' => 'hobby',       'type' => 'BLOG'],

            ['parent' => null, 'name' => 'agama islam', 'type' => 'BLOG'],

            ['parent' => 'programming', 'name' => '.NET',       'type' => 'BLOG'],
            ['parent' => '.NET', 'name' => 'C#',                'type' => 'BLOG'],
            ['parent' => '.NET', 'name' => 'ASPX dan ASPX MVC', 'type' => 'BLOG'],
            ['parent' => 'programming', 'name' => 'php',        'type' => 'BLOG'],
            ['parent' => 'php', 'name' => 'general php',        'type' => 'BLOG'],
            ['parent' => 'php', 'name' => 'laravel',        'type' => 'BLOG'],
            ['parent' => 'php', 'name' => 'code igniter',        'type' => 'BLOG'],
            ['parent' => 'php', 'name' => 'yii',        'type' => 'BLOG'],

            ['parent' => 'programming', 'name' => 'android',        'type' => 'BLOG'],
            ['parent' => 'android', 'name' => 'kotlin',        'type' => 'BLOG'],
            ['parent' => 'android', 'name' => 'java',        'type' => 'BLOG'],
            ['parent' => 'android', 'name' => 'react native',        'type' => 'BLOG'],
            ['parent' => 'android', 'name' => 'flutter',        'type' => 'BLOG'],

            ['parent' => 'programming', 'name' => 'javascript', 'type' => 'BLOG'],
            ['parent' => 'javascript', 'name' => 'jquery', 'type' => 'BLOG'],
            ['parent' => 'javascript', 'name' => 'reactjs', 'type' => 'BLOG'],
            ['parent' => 'javascript', 'name' => 'nodejs', 'type' => 'BLOG'],

            ['parent' => 'programming', 'name' => 'game programming', 'type' => 'BLOG'],
            ['parent' => 'game programming', 'name' => 'Unreal Engine',                'type' => 'BLOG'],
            ['parent' => 'game programming', 'name' => 'Unity', 'type' => 'BLOG'],
            ['parent' => 'game programming', 'name' => 'Godot', 'type' => 'BLOG'],

            ['parent' => 'hobby', 'name' => 'model kit',       'type' => 'BLOG'],
            ['parent' => 'hobby', 'name' => 'papercraft',       'type' => 'BLOG'],

            ['parent' => 'agama islam', 'name' => 'aqidah',       'type' => 'BLOG'],
            ['parent' => 'agama islam', 'name' => 'fiqih',       'type' => 'BLOG'],
            ['parent' => 'agama islam', 'name' => 'tarikh',       'type' => 'BLOG'],

            ['parent' => null, 'name' => 'pria', 'type' => 'JENIS_KELAMIN'],
            ['parent' => null, 'name' => 'wanita', 'type' => 'JENIS_KELAMIN'],

            ['parent' => null, 'name' => 'SD', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SMP', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SMU/K', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D-1', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D-3', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S-1', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S-2', 'type' => 'STRATA_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S-3', 'type' => 'STRATA_PENDIDIKAN'],

            ['parent' => null, 'name' => 'PAUD', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'TK / SEDERAJAT', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PUTUS SD', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SD / SEDERAJAT', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SMP / SEDERAJAT', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SMA / SEDERAJAT', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PAKET A', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PAKET B', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PAKET C', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PROFESI', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'PROFESI', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SP-1', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'TIDAK SEKOLAH', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D1', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D2', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D3', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'D4', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S1', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S2', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S3', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'NON FORMAL', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'INFORMAL', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => '(TIDAK DIISI)', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S2 TERAPAN', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'SP-2', 'type' => 'JENJANG_PENDIDIKAN'],
            ['parent' => null, 'name' => 'S3 TERAPAN', 'type' => 'JENJANG_PENDIDIKAN'],


            ['parent' => null, 'name' => 'single', 'type' => 'STATUS_PERKAWINAN'],
            ['parent' => null, 'name' => 'menikah', 'type' => 'STATUS_PERKAWINAN'],
            ['parent' => null, 'name' => 'janda/duda', 'type' => 'STATUS_PERKAWINAN'],

            ['parent' => null, 'name' => 'WNI', 'type' => 'KEWARGANEGARAAN'],
            ['parent' => null, 'name' => 'WNA', 'type' => 'KEWARGANEGARAAN'],

            ['parent' => null, 'name' => 'ISLAM', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'KRISTEN', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'KATHOLIK', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'HINDU', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'BUDHA', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'KHONGHUCU', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'TIDAK DIISI', 'type' => 'AGAMA'],
            ['parent' => null, 'name' => 'KEPERCAYAAN KPD TUHAN YME', 'type' => 'AGAMA'],

            ['parent' => null, 'name' => 'TIDAK BEKERJA', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'NELAYAN', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PETANI', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PETERNAK', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PNS/TNI/POLRI', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'KARYAWAN SWASTA', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PEDAGANG KECIL', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PEDAGANG BESAR', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'WIRASWASTA', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'WIRAUSAHA', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'BURUH', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'PENSIUNAN', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => '-', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'SUDAH MENINGGAL', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'TIDAK DAPAT DITERAPKAN', 'type' => 'JENIS_PEKERJAAN'],
            ['parent' => null, 'name' => 'TENAGA KERJA INDONESIA', 'type' => 'JENIS_PEKERJAAN'],

            ['parent' => null, 'name' => 'A', 'type' => 'AKREDITASI'],
            ['parent' => null, 'name' => 'B', 'type' => 'AKREDITASI'],
            ['parent' => null, 'name' => 'C', 'type' => 'AKREDITASI'],
            ['parent' => null, 'name' => 'TERAKREDITASI', 'type' => 'AKREDITASI'],
            ['parent' => null, 'name' => 'TIDAK TERAKREDITASI', 'type' => 'AKREDITASI'],
            ['parent' => null, 'name' => 'BELUM TERAKREDITASI', 'type' => 'AKREDITASI'],

            ['parent' => null, 'name' => 'ANAK ANGKAT', 'type' => 'STATUS_ANAK'],
            ['parent' => null, 'name' => 'ANAK TIRI', 'type' => 'STATUS_ANAK'],
            ['parent' => null, 'name' => 'ANAK KANDUNG', 'type' => 'STATUS_ANAK'],

            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'TENAGA HONOR SEKOLAH', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'GURU HONOR SEKOLAH', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'GURU BANTU PUSAT', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'HONOR DAERAH TK.II KAB/KOTA', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'HONOR DAERAH TK.I PROVINSI', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'GTY/PTY', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'PNS DEPAG', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'PNS DIPERBANTUKAN', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'PNS', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'CPNS', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'KONTRAK KERJA WNA', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'PPPK', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'GURU PENGGANTI', 'type' => 'STATUS_KEPEGAWAIAN'],
            ['parent' => null, 'name' => 'PPNPN', 'type' => 'STATUS_KEPEGAWAIAN'],

            ['parent' => null, 'name' => 'I/A', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'I/B', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'I/C', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'I/D', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'II/A', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'II/B', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'II/C', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'II/D', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'III/A', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'III/B', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'III/C', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'III/D', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'IV/A', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'IV/B', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'IV/C', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'IV/D', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => 'IV/E', 'type' => 'GOLONGAN'],
            ['parent' => null, 'name' => '-', 'type' => 'GOLONGAN'],

            ['parent' => null, 'name' => 'GURU PRATAMA, LL/A', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU PRATAMA TK I, LL/B', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MUDA, LL/C', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MUDA TK I, LL/D', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MADYA, LLL/A', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MADYA TK I, II L/B', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU DEWASA, LLL/C', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU DEWASA TK I, LLL/D', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU PEMBINA, IV/A', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU PEMBINA TK I, IV/B', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU UTAMA MUDA, IV/C', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU UTAMA MADYA, IV/D', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU UTAMA, IV/E', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU PERTAMA, LLL/A', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU PERTAMA, LLL/B', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MUDA, LLL/C', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MUDA, LLL/D', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MADYA, IV/A', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MADYA, IV/B', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU MADYA, IV/C', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU UTAMA, IV/D', 'type' => 'JABATAN_FUNGSIONAL'],
            ['parent' => null, 'name' => 'GURU UTAMA, IV/E', 'type' => 'JABATAN_FUNGSIONAL'],


            ['parent' => null, 'name' => 'GURU', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA SEKOLAH', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA PERPUSTAKAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TENAGA PERPUSTAKAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA TENAGA ADMINISTRASI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TENAGA ADMINISTRASI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA LABORATORIUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TEKNISI LABORATORIUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'LABORAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGAWAS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TIDAK DIISI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'WAKIL KEPALA SEKOLAH', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'BENDAHARA', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PUSTAKAWAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PESURUH/PENJAGA SEKOLAH', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TUTOR KESETARAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PAMONG BELAJAR', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TLD', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA PKBM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENDIDIK PAUD', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENILIK', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'INSTRUKTUR KURSUS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TUTOR PAKET A', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TUTOR PAKET B', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TUTOR PAKET C', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA LAB (NON GURU)', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA PERPUSTAKAAN (NON GURU)', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TUTOR KEAKSARAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA KURSUS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA KEAKSARAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA PAUD', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA KESETARAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGELOLA TBM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PLT KEPALA SEKOLAH', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'WAKIL KEPALA SEKOLAH KESISWAAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'WAKIL KEPALA SEKOLAH SARPRAS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'WAKIL KEPALA SEKOLAH HUMAS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA BENGKEL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA PROGRAM KEAHLIAN', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KEPALA UNIT PRODUKSI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KOORDINATOR LABORATORIUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'GURU PIKET', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PEMBINA PRAMUKA PUTRA', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PEMBINA PRAMUKA PUTRI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PEMBINA OSIS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PEMBINA EKSTRAKURIKULER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'WAKIL KEPALA SEKOLAH KURIKULUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'INSTRUKTUR NASIONAL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'NARASUMBER NASIONAL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TIM PENGEMBANG KURIKULUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MENTOR DIKLAT/KURIKULUM', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PRINCIPAL FOR SENIOR HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'VICE PRINCIPAL FOR SENIOR HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PRINCIPAL FOR JUNIOR HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'VICE PRINCIPAL FOR JUNIOR HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PRINCIPAL FOR ELEMENTARY SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'VICE PRINCIPAL FOR ELEMENTARY SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ACADEMIC ADVISOR', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MANAGEMENT ADVISOR', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'CURRICULUM DEVELOPMENT ADVISOR', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ACADEMIC SPECIALIST FOR E. SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ACADEMIC SPECIALIST FOR J.HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ACADEMIC SPECIALIST FOR S.HIGH SCHOOL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ARABIC TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ISLAMIC STUDY TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'DUTCH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MANDARIN (CHINESE) TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ENGLISH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'JAPANESE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KOREAN TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'DEUTSCH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'FRENCH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TURKISH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'HINDI TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PHYSIC TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'BIOLOGY TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MATHEMATICS TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'BUSINESS STUDY TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ECONOMICS TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MUSIC TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'GEOGRAPHY TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'SCIENCE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ART TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'HEALTH TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'ART AND MUSIC TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'SKILLS TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'COMPUTER TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PHYSICAL EDUCATION TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'MORAL ETHIC TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '6 TH GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '5 TH GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '4 TH GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '3 RD GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '2 ND GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => '1ST GRADE TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PLAY GROUP TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KINDERGARTEN TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'SPECIAL NEEDS TEACHER', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'TEACHING ASSISTANT', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KOORDINATOR PENGEMBANGAN PKB/PKG', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KOORDINATOR BURSA KERJA KHUSUS SMK', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'KETUA LPS-P1 UNTUK SMK', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENILAIAN KINERJA GURU', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGURUS ORGANISASI TINGKAT NASIONAL', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGURUS ORGANISASI TINGKAT PROPINSI', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PENGURUS ORGANISASI TINGKAT KABUPATEN / KOTA', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'BENDAHARA BOS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'GURU PEMBIMBING KHUSUS', 'type' => 'JABATAN_TUGAS_PTK'],
            ['parent' => null, 'name' => 'PELAKSANA PBJ', 'type' => 'JABATAN_TUGAS_PTK'],

            ['parent' => null, 'name' => 'SISWA BARU', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'PINDAHAN', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'NAIK KELAS', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'AKSELERASI', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'MENGULANG', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'LANJUTAN SEMESTER', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'PUTUS SEKOLAH', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'JENIS_PENDAFTARAN'],
            ['parent' => null, 'name' => 'KEMBALI BERSEKOLAH', 'type' => 'JENIS_PENDAFTARAN'],

            ['parent' => null, 'name' => 'Kartu Tanda Penduduk (KTP)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Kartu Keluarga (KK)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Nomor Pokok Wajib Pajak  (NPWP)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Keterangan Domisili Usaha (SKDU)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Izin Usaha Dagang (UD)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Tempat Usaha (SITU)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Prinsip', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Prinsip - Perluasan', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Prinsip - Perubahan', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Prinsip - Penggabungan / Merger', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Usaha Industri (SIUI)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Usaha Perdagangan (SIUP)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Tanda Daftar Perusahaan (TDP)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Tanda Daftar Industri (TDI)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'HO Surat izin gangguan', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Surat Izin Mendirikan Bangunan (IMB)', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Izin BPOM', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Sertifikasi Halal', 'type' => 'JENIS_DOKUMEN'],
            ['parent' => null, 'name' => 'Salinan Buku Rekening Bank', 'type' => 'JENIS_DOKUMEN'],

            ['parent' => null, 'name' => 'RUANG TEORI/KELAS', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM IPA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM KIMIA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM FISIKA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM BIOLOGI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM BAHASA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM IPS', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM KOMPUTER', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM MULTIMEDIA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG PERPUSTAKAAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG PERPUSTAKAAN MULTIMEDIA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG KETERAMPILAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG SERBA GUNA/AULA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG UKS', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG PRAKTIK KERJA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'BENGKEL', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG DIESEL', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG PAMERAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG GAMBAR', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KOPERASI/TOKO', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BP/BK', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG KEPALA SEKOLAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG GURU', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG TU', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG OSIS', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KAMAR MANDI/WC GURU LAKI-LAKI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KAMAR MANDI/WC GURU PEREMPUAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KAMAR MANDI/WC SISWA LAKI-LAKI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KAMAR MANDI/WC SISWA PEREMPUAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'GUDANG', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG IBADAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUMAH DINAS KEPALA SEKOLAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUMAH DINAS GURU', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUMAH PENJAGA SEKOLAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'SANGGAR MGMP', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'SANGGAR PKG', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'ASRAMA SISWA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'UNIT PRODUKSI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG MULTIMEDIA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG PUSAT BELAJAR GURU', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG OLAHRAGA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LAINNYA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG ORIENTASI DAN MOBILITAS (OM)', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BINA WICARA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BINA PERSEPSI BUNYI DAN IRAMA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BINA DIRI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BINA DIRI DAN BINA GERAK', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG BINA PRIBADI DAN SOSIAL', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG KETERAMPILAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG KONSELING/ASESMEN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG TERAPI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM NAUTIKA', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LABORATORIUM BAHARI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG SIRKULASI', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KAMAR MANDI/WC UMUM', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LAPANGAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LAPANGAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'PARKIR', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KANTIN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'LAHAN KOSONG', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'TANAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'BANGUNAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'BANGUNAN TEMPAT IBADAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'TAMAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'TEMPAT BERMAIN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG IBADAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KEBUN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'RUANG IBADAH', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'TAMAN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'KEBUN', 'type' => 'JENIS_PRASARANA'],
            ['parent' => null, 'name' => 'TEMPAT BERMAIN', 'type' => 'JENIS_PRASARANA'],

            ['parent' => null, 'name' => 'GANJIL', 'type' => 'JENIS_SEMESTER'],
            ['parent' => null, 'name' => 'GENAP', 'type' => 'JENIS_SEMESTER'],

            ['parent' => null, 'name' => 'ZONASI', 'type' => 'JALUR_PPDB'],
            ['parent' => null, 'name' => 'AFFIRMASI', 'type' => 'JALUR_PPDB'],
            ['parent' => null, 'name' => 'PERPINDAHAN TUGAS', 'type' => 'JALUR_PPDB'],

            ['parent' => null, 'name' => 'KELAS 1', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 2', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 3', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 4', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 5', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 6', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 7', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 8', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 9', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 10', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 11', 'type' => 'KELAS'],
            ['parent' => null, 'name' => 'KELAS 12', 'type' => 'KELAS'],
        ];

        $stipe = [];
        foreach($type as $tipe) {
            $stipe[$tipe["type"]] = \Irfansjah\Gtx\Models\EntityCategoryType::where('type',$tipe["type"])->first()->id;
        }
        foreach($kategori as $cat) {
            $s = ['name' => $cat['name'], 'type_id'=> $stipe[$cat['type']]];
            \Irfansjah\Gtx\Models\Category::create($s);
        }
    }
}
